version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
volumes:
  db:
    driver: local