version: '3.3'
services:
  cache:
    image: redis
    #   image: redis:6.2-alpine
    restart: always
    ports:
      - '56379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local