version: '3.1'

services:

  mongodb:
    image: mongo
    restart: always
    ports:
      - 57017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: zxc,./,./

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 58081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: zxc,./,./
      ME_CONFIG_MONGODB_SeERVER: mongodb